apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memshack-operator
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - memshack-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - example.memcached.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - example.memshack.com
  resources:
  - '*'
  - memshacks
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memshack-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memshack-operator
subjects:
- kind: ServiceAccount
  name: memshack-operator
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memshack-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memshack-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: memshack-operator
  template:
    metadata:
      labels:
        name: memshack-operator
      name: memshack-operator
    spec:
      containers:
      - image: memshack-operator:latest
        imagePullPolicy: Never
        name: operator
        ports:
        - containerPort: 3000
          name: https
          protocol: TCP
      serviceAccountName: memshack-operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: memshacks.example.memshack.com
spec:
  group: example.memshack.com
  names:
    categories: []
    kind: Memshack
    plural: memshacks
    shortNames: []
    singular: memshack
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MemshackSpec via `CustomResource`
        properties:
          spec:
            properties:
              mcrouter_image:
                default: mcrouter/mcrouter:latest
                type: string
              mcrouter_pool_size:
                default: 2
                format: uint
                minimum: 0.0
                type: integer
              mcrouter_port:
                default: 5000
                format: uint
                minimum: 0.0
                type: integer
              memcached_image:
                default: memcached:1.6-alpine
                type: string
              num_replicas:
                default: 2
                format: uint
                minimum: 0.0
                type: integer
              num_shards:
                default: 3
                format: uint
                minimum: 0.0
                type: integer
            type: object
          status:
            nullable: true
            properties:
              message:
                type: string
              phase:
                type: string
            required:
            - message
            - phase
            type: object
        required:
        - spec
        title: Memshack
        type: object
    served: true
    storage: true
    subresources:
      status: {}
